services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=inscription-service'
      - 'POSTGRES_PASSWORD=nnr@'
      - 'POSTGRES_USER=nnr'
    ports:
      - '9001:5432'
