# Port d'écoute du serveur Eureka
server.port=8761

# Configuration Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Actuator pour la surveillance
management.endpoints.web.exposure.include=*