# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:9000/utilisateur-service
spring.datasource.username=nnr
spring.datasource.password=nnr@
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration Eureka pour la découverte de services
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Exposition des endpoints Actuator pour la surveillance
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#serveur du port tomcat au demarrage
server.port=1501


