spring.application.name=config-service
server.port=8000

# specifie l'url git ou se trouvent l'ensemble des fichiers de config de nos microservice.
# on peut aussi le faire a travers un dossier local
spring.cloud.config.server.git.uri=file://${user.home}/cloud-config

# depot git master et non main
spring.cloud.config.server.git.default-label=master

