spring.application.name=eureka-config-service

#recupere sa config sur le serveur de config centralisee
spring.cloud.config.uri=http://localhost:8000

#Permet à utilisateur-service d?importer sa configuration depuis le config-server.
spring.config.import=configserver:
