spring.application.name=proxy-config-service

server.port=8089

# Configuration pour Eureka (découverte des services)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

#recupere sa config sur le serveur de config centralisee
#spring.cloud.config.uri=http://localhost:8000

#Permet à utilisateur-service d?importer sa configuration depuis le config-server.
#spring.config.import=configserver:


# Exemple pour rediriger vers le service utilisateur (nom enregistré dans Eureka)
spring.cloud.gateway.routes[0].id=utilisateur-service
spring.cloud.gateway.routes[0].uri=lb://utilisateur-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/utilisateur-service/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/utilisateur-service/(?<segment>.*), /${segment}

#Exemple pour rediriger vers le service inscription (nom enregistré dans Eureka)
# Route pour inscription-services
spring.cloud.gateway.routes[1].id=inscription-services
spring.cloud.gateway.routes[1].uri=lb://inscription-services
spring.cloud.gateway.routes[1].predicates[0]=Path=/inscription-services/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/inscription-services/(?<segment>.*), /${segment}

# Route pour cours-service
spring.cloud.gateway.routes[2].id=cours-service
spring.cloud.gateway.routes[2].uri=lb://cours-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/cours-service/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/cours-service/(?<segment>.*), /${segment}
